server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 120.79.136.105
                port: 5672
                username: guest
                password: guest

      bindings: # 声明channel 对应的[交换机、binder（mq的环境）、创建队列]
        input:  # 一个通道的名字 channelName
          destination: studyExchange  # 交换机
          content-type: application/json
          bander: defaultRabbit # 指定环境
          group: myGroup-A  # 在上面的交换机上创建一个队列（分组）

        trade-input:
          destination: studyExchange  # 交换机
          content-type: application/json
          bander: defaultRabbit
          group: myGroup-B  # 在上面的交换机上创建一个队列（分组），名称为： destination.group

      rabbit:
        bindings:
          input:  # 绑定 channel 和 路由key,
            consumer:
              bindingRoutingKey: normal

          trade-input:
            consumer:
              bindingRoutingKey: trade

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   # 表示要往哪个地方注册自己的信息
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: receive-8802.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

