server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider-service
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.136.105:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
