server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   # 表示要往哪个地方注册自己的信息
  instance:
    instance-id: order80  #服务名称
    prefer-ip-address: true #开启服务显示的ip


feign:
  client:
    config:
      cloud-payment-service:  # 指定这个服务的 超时以及日志的级别
        connectTimeout: 5000  # feign 超时
        readTimeout: 5000
        loggerLevel: full     # 日志级别（详细程度）


logging:
  level:  # 指定哪些类或者方法开启日志打印
    com.cca.springcloud.service.PaymentServiceFeign: debug
    com.cca.springcloud.controller.OrderController: debug